# App Name
spring.application.name=EAC_HR_Admission

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/eac_hr_db
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update 
# Set to 'none' because we are using Stored Procedures and existing tables

# Email Settings (You need a Gmail App Password for this to work)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=franklinmoris22@gmail.com
spring.mail.password=kbpp jpvh sida xbdc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.thymeleaf.cache=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true